version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123!
      POSTGRES_DB: esm-db
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
